---
- name: Create onos-ansible-help.txt
  template:
    src: "onos-start.sh.j2"
    dest: "{{ HOME_PATH }}"
    mode: 0644

- name: Copy onos-cheat-sheat.txt
  file:
    src: "onos-cheat-sheat.txt"
    dest: "{{ HOME_PATH }}"
    mode: 0644

