---
- hosts: onos-master
  vars_files:
    - group_vars/version.yml
    - group_vars/config.yml
  roles:
    - apt
    - ntp
    - java
    - maven
    - karaf
    - bashrc
    - onos
    - cell
    - help
