---
- hosts: all
  vars_files:
    - group_vars/version.yml
    - group_vars/config.yml
  roles:
    - apt
    - ntp
    - hosts
    - java

- hosts: onos-master
  vars_files:
    - group_vars/version.yml
    - group_vars/config.yml
  roles:
    - maven
    - karaf
    - onos_env
    - onos
    - cell
    - help

