---
- hosts: onos-master
  remote_user: root
  vars_files:
    - group_vars/version
    - group_vars/config
  roles:
    - apt
    - ntp
    - java
    - maven
    - karaf
    - bashrc
    - onos
    - cell
    - help
