---
- name: Set variable for Apache Karaf
  set_fact:
    KARAF_MIRROR: "http://archive.apache.org/dist/karaf/{{ KARAF_VERSION }}/apache-karaf-{{ KARAF_VERSION }}.tar.gz"
  tags: karaf

- name: Create Downloads directory
  file: path={{ DOWNLOADS_PATH }} state=directory
  tags: karaf
 
- name: Create Applications directory
  file: path={{ APPLICATIONS_PATH }} state=directory                                                                                             
  tags: karaf

- name: Download Apache Karaf
  get_url:
    url: "{{ KARAF_MIRROR }}"
    dest: "{{ DOWNLOADS_PATH }}" 
  tags: karaf

- name: Untar Apache Karaf
  unarchive:
    src: "{{ DOWNLOADS_PATH }}/apache-karaf-{{ KARAF_VERSION }}.tar.gz"
    dest: "{{ APPLICATIONS_PATH }}"
  tags: karaf
