- name: Replace APT source list
  replace:
    dest=/etc/apt/sources.list
    regexp=us.archive.ubuntu.com
    replace=ubuntu.cs.nctu.edu.tw
    backup=yes
  sudo: yes
  tags: apt

- name: Update APT Cache
  apt: update_cache=yes
  sudo: yes
  tags: apt
